//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DthK22CNT4Lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DthAccount
    {
        public int DthId { get; set; }
        public string DthUserName { get; set; }
        public string DthPassword { get; set; }
        public string DthFullName { get; set; }
        public string DthEmail { get; set; }
        public string DthPhone { get; set; }
        public Nullable<bool> DthActive { get; set; }
    }
}
