//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DthK22CNT4Lesson11_221900028.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DthK22CNT4Lesson11DbEntities : DbContext
    {
        public DthK22CNT4Lesson11DbEntities()
            : base("name=DthK22CNT4Lesson11DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DthCategory> DthCategories { get; set; }
        public virtual DbSet<DthProduct> DthProducts { get; set; }
    }
}
