//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DthK22CNT4Lesson11_221900028.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DthCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DthCategory()
        {
            this.DthProducts = new HashSet<DthProduct>();
        }
        [Display(Name ="Mã danh mục")]
        public int DthID { get; set; }
        [Display(Name = "Tên danh mục")]
        public string DthCateName { get; set; }

        [Display(Name = "Trạng thái")]
        public Nullable<bool> DthStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DthProduct> DthProducts { get; set; }
    }
}
