//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DthK22CNT4Lesson11_221900028.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DthProduct
    {
        public string DthId { get; set; }
        public string DthProName { get; set; }
        public Nullable<int> DthQty { get; set; }
        public Nullable<double> Dthprice { get; set; }
        public Nullable<int> DthCateId { get; set; }
        public Nullable<bool> DthActive { get; set; }
    
        public virtual DthCategory DthCategory { get; set; }
    }
}
