//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DthLesson07DF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class dthKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dthKhoa()
        {
            this.dthSinhViens = new HashSet<dthSinhVien>();
        }
        [Required(ErrorMessage = "Hãy nhập mã khoa")]
        [DisplayName("Mã khoa")]
        [DataType(DataType.Currency)]
        public string DthMaKhoa { get; set; }

        [Required(ErrorMessage = "Hãy nhập tên khoa")]
        [DisplayName("Tên khoa")]
        [DataType(DataType.Currency)]
        public string DthTenKhoa { get; set; }

        [Required(ErrorMessage = "Hãy chọn trạng thái")]
        [DataType(DataType.Currency)]
        public Nullable<bool> DthTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dthSinhVien> dthSinhViens { get; set; }
    }
}
