//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DthLesson07DF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dthSinhVien
    {
        public string DthMaSV { get; set; }
        public string DthHoSV { get; set; }
        public string DthTenSV { get; set; }
        public Nullable<System.DateTime> DthNgaySinh { get; set; }
        public Nullable<bool> DthPhai { get; set; }
        public string DthPhone { get; set; }
        public string DthEmail { get; set; }
        public string DthMaKh { get; set; }
    
        public virtual dthKhoa dthKhoa { get; set; }
    }
}
