//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DthLesson08LtDF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DthKetQua
    {
        public int MaKQ { get; set; }
        public string MaSV { get; set; }
        public string MaMH { get; set; }
        public Nullable<double> Diem { get; set; }
    
        public virtual DthMonHoc DthMonHoc { get; set; }
        public virtual DthSinhVien DthSinhVien { get; set; }
    }
}
