//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DthLesson08LtDF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DthMonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DthMonHoc()
        {
            this.DthKetQuas = new HashSet<DthKetQua>();
        }
    
        public string MaMH { get; set; }
        public string TenMh { get; set; }
        public Nullable<int> SoTiet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DthKetQua> DthKetQuas { get; set; }
    }
}
