//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DthLesson08LtDF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dth_qlSinhVienEntities : DbContext
    {
        public Dth_qlSinhVienEntities()
            : base("name=Dth_qlSinhVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DthKetQua> DthKetQuas { get; set; }
        public virtual DbSet<DthKhoa> DthKhoas { get; set; }
        public virtual DbSet<DthMonHoc> DthMonHocs { get; set; }
        public virtual DbSet<DthSinhVien> DthSinhViens { get; set; }
    }
}
